name: Build & Deploy Frontend

on:
  push:
    branches: [master]
    paths:
      - 'frontend/**'

defaults:
  run:
    working-directory: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install all dependencies
        run: npm ci

      - name: Build app to ./dist
        run: npm run build

      - name: Install Rsync
        run: sudo apt install rsync

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: RSync ./dist To Sylvanas
        run: rsync -Pav --rsync-path="sudo rsync" --delete -e "ssh -o StrictHostKeyChecking=no" dist/* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOSTNAME }}:/var/www/renshou.bednarski.dev/

